### ISSUE TITLE
C code clean-up

### ISSUE THREAD

**Issue by MsVerina** [aholinch/sgp4#4]
Suggest some clean-ups to remove compiler warnings...  I applied this locally in a "c-code_clean-up" branch...
In file: SGP4.c line 245
                if (fabs(xnoh - rec->nodep) > pi) {
                    if (rec->nodep < xnoh) 
                    {
                        rec->nodep = rec->nodep + twopi;
                    } 
                    else
                    {
                        rec->nodep = rec->nodep - twopi;
                    }
                }

**Comment by aholinch** [comment]
Thank you, MsVerina.  
I was able to make a quick edit.  
Feel free to fork the code and make the C version (or any language version) exactly what you want it to be.

**Comment by AmorBielyi** [comment]
@aholinch  @MsVerina  Hi Anthony, hi Ashley, this repo and your contributions to the SGP4 algorithms in different languages is very valuable for me, many thanks!

I'd also really value your feedback on a project I've been working on. I think you might find it interesting because it's related to USSF SGP4:

XPropagator - a modern satellite orbit propagation service exposing the official USSF SGP4/SGP4-XP propagator via a powerful gRPC API - designed for SSA pipelines and modern microservices architectures. Features include catalog-scale satellite processing, streaming ephemeris generation, and built-in memory management with garbage collection. It's written in Go/Cgo

Link: https://github.com/xpropagation/xpropagator

I'd appreciate any thoughts, suggestions, or critique you might have.
Thanks in advance!
